### ISSUE TITLE
[deploy] ci/cd 적용

### ISSUE THREAD

**Issue by Parkjyun** [Parkjyun/NewSnack-Server#1]
---
## Issue 📌
- ci cd 적용
## Todo ✔️
- [ ] ci.yml 생성
- [ ] cd.yml 생성
- [ ] githubsecrets 작성
- [ ] deploy.sh 생성
